# WIP - ON-1115/ON-1117
# recommended IDE: VSCode + Github Actions extension
name: bucket deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy"
        type: environment
        required: true
      note:
        description: "Notes - eg. Version 1.177, point release, etc."
        type: string
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  preflight:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: log variables
        run: |
          echo "NOTE: inputs.note [${{ inputs.note }}]"
          echo "CONFIGURATION: inputs.environment [${{ inputs.environment }}] (user choice)"
          echo "CONFIGURATION: vars.NODE_VERSION [${{ vars.NODE_VERSION }}] (defined in repository)"
          echo "CONFIGURATION: Bucket sync for bucket [${{ toJSON(vars) }}] (defined in repository and environment variables)"
          echo "CONDITION: ${{ vars.BUCKET != '' && vars.NODE_VERSION != '' && vars.APP_NAME_FOR_CDN != '' && vars.APP_NAME_FOR_CDN != '/'}}"
      #precondition, repeated below (in deploy) for redundancy
      #missing a check can result in bad rsync removing content not owned by this workflow
      - name: verify all variables
        if: ${{ vars.BUCKET == '' || vars.APP_NAME_FOR_CDN == '' || vars.APP_NAME_FOR_CDN == '/'}}
        run: |
          echo "ERROR!! condition [vars.BUCKET == '' || vars.APP_NAME_FOR_CDN == '' || vars.APP_NAME_FOR_CDN == '/'] not met"
          exit 1

  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: preflight

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Authenticate with Google Cloud Workload Identity
        uses: google-github-actions/auth@v2
        with:
          project_id: "orgmgt-cicd"
          workload_identity_provider: "projects/578309997731/locations/global/workloadIdentityPools/github/providers/github-impactinc"

      - name: Authenticate with GCP and install packages
        run: |
          npx google-artifactregistry-auth --repo-config=./.npmrc --credential-config=$HOME/.npmrc
          npm ci

      - name: npm build, and test
        run: |
          npm run build --if-present
          npm run test --if-present

      - name: npm save build info
        run: |
          npm run saveBuildInfo

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./dist

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: none

    needs: build
    environment: ${{ inputs.environment }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: node-app-distribution

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GSJS }}"

      - name: Setup Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: log if environment vars.BUCKET missing
        if: ${{ vars.BUCKET == '' || vars.APP_NAME_FOR_CDN == '' || vars.APP_NAME_FOR_CDN == '/'}}
        run: |
          echo "ERROR!! condition [vars.BUCKET == '' || vars.APP_NAME_FOR_CDN == '' || vars.APP_NAME_FOR_CDN == '/'] not met"
          exit 1

      - name: log command
        if: ${{ vars.BUCKET != '' && vars.APP_NAME_FOR_CDN != '' && vars.APP_NAME_FOR_CDN != '/'}}
        run: |
          echo 'gsutil rsync -r -d -a public-read ./node-app-distribution/ "gs://platform-assets-ui/${{ vars.APP_NAME_FOR_CDN }}/${{ vars.BUCKET }}"'
          echo 'gsutil -m setmeta -h "Cache-Control:no-cache, max-age=0, no-transform" -r "gs://platform-assets-ui/${{ vars.APP_NAME_FOR_CDN }}/${{ vars.BUCKET }}/"'

      - name: Rsync Google Cloud Storage
        if: ${{ vars.BUCKET != '' && vars.APP_NAME_FOR_CDN != '' && vars.APP_NAME_FOR_CDN != '/'}}
        run: |
          gsutil rsync -r -d -a public-read ./node-app-distribution/ "gs://platform-assets-ui/${{ vars.APP_NAME_FOR_CDN }}/${{ vars.BUCKET }}"
          gsutil -m setmeta -h "Cache-Control:no-cache, max-age=0, no-transform" -r "gs://platform-assets-ui/${{ vars.APP_NAME_FOR_CDN }}/${{ vars.BUCKET }}/"
