# recommended IDE: VSCode + Github Actions extension
name: Storybook Branch Deployment

on:
  workflow_dispatch:
    inputs:
      note:
        description: "Reason for deployment (optional)"
        type: string
        required: false

permissions:
  id-token: write
  contents: read

jobs:
  preflight:
    runs-on: ubuntu-latest

    steps:
      - name: log variables
        run: |
          echo "BRANCH: [${{ github.ref_name }}]"
          echo "NOTE: inputs.note [${{ inputs.note }}]"
          echo "CONFIGURATION: vars.NODE_VERSION [${{ vars.NODE_VERSION }}] (defined in repository)"
          echo "CONDITION: ${{ github.ref_name != '' && vars.NODE_VERSION != '' && vars.APP_NAME_FOR_CDN != '' && vars.APP_NAME_FOR_CDN != '/'}}"
      #precondition, repeated below (in deploy) for redundancy
      #missing a check can result in bad rsync removing content not owned by this workflow
      - name: verify all variables
        if: ${{ github.ref_name == '' || vars.APP_NAME_FOR_CDN == '' || vars.APP_NAME_FOR_CDN == '/' }}
        run: |
          echo "ERROR!! condition [github.ref_name == '' || vars.APP_NAME_FOR_CDN == '' || vars.APP_NAME_FOR_CDN == '/'] not met"
          exit 1

  build:
    runs-on: ubuntu-latest
    needs: preflight

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ vars.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Authenticate with Google Cloud Workload Identity
        uses: google-github-actions/auth@v2
        with:
          project_id: "orgmgt-cicd"
          workload_identity_provider: "projects/578309997731/locations/global/workloadIdentityPools/github/providers/github-impactinc"

      - name: Authenticate with GCP and install packages
        run: |
          npx google-artifactregistry-auth --repo-config=./.npmrc --credential-config=$HOME/.npmrc
          npm ci

      - name: npm build
        run: |
          npm run storybook:build

      - name: npm save build info
        run: |
          npm run saveBuildInfo

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: storybook-node-app
          path: ./dist

  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: none

    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: storybook-node-app
          path: node-app-distribution

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GSJS }}"

      - name: Setup Google Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"

      - name: log if environment ref_name, APP_NAME_FOR_CDN missing
        if: ${{ github.ref_name == '' || vars.APP_NAME_FOR_CDN == '' || vars.APP_NAME_FOR_CDN == '/'}}
        run: |
          echo "ERROR!! condition [github.ref_name == '' || vars.APP_NAME_FOR_CDN == '' || vars.APP_NAME_FOR_CDN == '/'] not met"
          exit 1

      - name: log command if environment ref_name, APP_NAME_FOR_CDN missing
        if: ${{ github.ref_name != '' && vars.APP_NAME_FOR_CDN != '' && vars.APP_NAME_FOR_CDN != '/'}}
        run: |
          echo "branch: ${{ github.ref_name }}"
          echo 'gsutil rsync -r -d -a public-read ./node-app-distribution/ "gs://platform-assets-ui/${{ vars.APP_NAME_FOR_CDN }}/_storybook/${{ github.ref_name }}"'
          echo 'gsutil -m setmeta -h "Cache-Control:no-cache, max-age=0, no-transform" -r "gs://platform-assets-ui/${{ vars.APP_NAME_FOR_CDN }}/_storybook/${{ github.ref_name }}/"'

      - name: Rsync Google Cloud Storage
        if: ${{ github.ref_name != '' && vars.APP_NAME_FOR_CDN != '' && vars.APP_NAME_FOR_CDN != '/'}}
        run: |
          gsutil rsync -r -d -a public-read ./node-app-distribution/ "gs://platform-assets-ui/${{ vars.APP_NAME_FOR_CDN }}/_storybook/${{ github.ref_name }}"
          gsutil -m setmeta -h "Cache-Control:no-cache, max-age=0, no-transform" -r "gs://platform-assets-ui/${{ vars.APP_NAME_FOR_CDN }}/_storybook/${{ github.ref_name }}/"
